name: advent_of_code
description: Solutions for Advent of Code

environment:
  sdk: ^3.11.0

workspace:
 - year/2024
 - year/2025

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.30.0
