name: advent_of_code
description: Solutions for Advent of Code

environment:
  sdk: ^3.11.0

workspace:
 - year/2015
 - year/2016
 - year/2017
 - year/2018
 - year/2019
 - year/2020
 - year/2021
 - year/2022
 - year/2023
 - year/2024
 - year/2025

dependencies:
  any_base: ^2.0.0
  crypto: ^3.0.0
  collection: ^1.19.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
