name: advent_of_code_2019
description: Solutions for Advent of Code 2019.

environment:
  sdk: "^3.11.0"

resolution: workspace

dependencies:
  collection:

dev_dependencies:
  advent_of_code:
  test:
